cd "c:/Users/80233596/Desktop/A-Eye/firmware/build"
SET ALLUSERSPROFILE=C:\ProgramData
SET APPDATA=C:\Users\80233596\AppData\Roaming
SET BSPRINT_CLIENT=C:/Users/80233596/AppData/Roaming/Brocadesoft
SET CLASSPATH=.;C:\Program Files\Java\jdk1.8.0_131\\lib\dt.jar;C:\Program Files\Java\jdk1.8.0_131\\lib\tools.jar;
SET CommonProgramFiles=C:\Program Files\Common Files
SET CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
SET CommonProgramW6432=C:\Program Files\Common Files
SET COMPUTERNAME=PA80233596
SET ComSpec=C:\Windows\system32\cmd.exe
SET DriverData=C:\Windows\System32\Drivers\DriverData
SET HOMEDRIVE=C:
SET HOMEPATH=\Users\80233596
SET INTEL_DEV_REDIST=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\
SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0_131\
SET KENDRYTE_IDE_LOCAL_PACKAGE_DIR=C:\Green\KendryteIDE\LocalPackage
SET KENDRYTE_IDE_UPDATER=C:\Green\KendryteIDE\Updater\electron.exe
SET KENDRYTE_IDE_UPDATER_CONTENT_ROOT=C:\Green\KendryteIDE
SET KENDRYTE_IDE_UPDATER_IS_BUILT=yes
SET KENDRYTE_IDE_UPDATER_PIPE=\\?\pipe\C:\Users\80233596\AppData\Local\Temp\KendryteIDE_Cache\29827_updater.sock
SET KENDRYTE_IDE_UPDATER_PIPE_ID=1
SET LOCALAPPDATA=C:\Users\80233596\AppData\Local
SET LOGONSERVER=\\DCAPPW001CN
SET MIC_LD_LIBRARY_PATH=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\compiler\lib\intel64_win_mic
SET NUMBER_OF_PROCESSORS=8
SET OneDrive=C:\Users\80233596\OneDrive
SET OneDriveConsumer=C:\Users\80233596\OneDrive
SET OS=Windows_NT
SET Path=c:\Green\KendryteIDE\bin;C:\Green\KendryteIDE\LocalPackage\toolchain\bin;C:\Green\KendryteIDE\LocalPackage\cmake\bin;C:\Green\KendryteIDE\LocalPackage\jlink;C:\Green\KendryteIDE\LocalPackage\clang-format\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH
SET PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
SET PROCESSOR_ARCHITECTURE=AMD64
SET PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
SET PROCESSOR_LEVEL=6
SET PROCESSOR_REVISION=5e03
SET ProgramData=C:\ProgramData
SET ProgramFiles=C:\Program Files
SET ProgramFiles(x86)=C:\Program Files (x86)
SET ProgramW6432=C:\Program Files
SET PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
SET PUBLIC=C:\Users\Public
SET SESSIONNAME=Console
SET SystemDrive=C:
SET SystemRoot=C:\Windows
SET SYSTEM_TEMP=C:\Users\80233596\AppData\Local\Temp
SET TEMP=C:\Users\80233596\AppData\Local\Temp\KendryteIDE_Cache
SET TMP=C:\Users\80233596\AppData\Local\Temp\KendryteIDE_Cache
SET TMPDIR=C:\Users\80233596\AppData\Local\Temp\KendryteIDE_Cache
SET USERDNSDOMAIN=ADC.COM
SET USERDOMAIN=ADC
SET USERDOMAIN_ROAMINGPROFILE=ADC
SET USERNAME=80233596
SET USERPROFILE=C:\Users\80233596
SET VSCODE_CWD=C:\Green\KendryteIDE\Updater
SET VSCODE_IPC_HOOK=\\.\pipe\c033a517a7d8362c85e48f199f1ea823-1.34.1-beta-main-sock
SET VSCODE_LOGS=C:\Green\KendryteIDE\UserData\latest\user-data\logs\20191003T161039
SET VSCODE_NLS_CONFIG={"locale":"zh-cn","availableLanguages":{"*":"zh-cn"},"_languagePackId":"2ae16f5a9a23c98b985a67d503c3ac22.zh-cn","_translationsConfigFile":"C:\\Green\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\tcf.json","_cacheRoot":"C:\\Green\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn","_resolvedLanguagePackCoreLocation":"C:\\Green\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\e4de46724de34a5f46541818e9fee25971ac9969","_corruptedFile":"C:\\Green\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\corrupted.info","_languagePackSupport":true}
SET VSCODE_NODE_CACHED_DATA_DIR=C:\Green\KendryteIDE\UserData\latest\user-data\CachedData\e4de46724de34a5f46541818e9fee25971ac9969
SET VSCODE_PATH=C:\Green\KendryteIDE\Application\app_1.34.1-beta_20190802.2
SET VSCODE_PID=20164
SET VSCODE_PORTABLE=C:\Green\KendryteIDE\UserData\latest
SET windir=C:\Windows
SET XILINX_FOR_ALTIUM_OVERRIDE= 
SET PYTHONHOME=C:/Green/KendryteIDE/LocalPackage/python2library
SET PYTHONPATH=C:/Green/KendryteIDE/LocalPackage/python2library;C:/Green/KendryteIDE/LocalPackage/toolchain/share/gdb/python
SET PYTHONDONTWRITEBYTECODE=yes
SET CMAKE_MAKE_PROGRAM=make
SET KENDRYTE_IDE=yes
SET LANG=en_US.utf-8
"C:/Green/KendryteIDE/LocalPackage/cmake/bin/cmake.exe" --build c:/Users/80233596/Desktop/A-Eye/firmware/build -- -j 7