cd "c:/Users/Pengzhihui/Desktop/Tmp/A-Eye/firmware/build"
SET ACTEL_FOR_ALTIUM_OVERRIDE= 
SET ALLUSERSPROFILE=C:\ProgramData
SET ALTERA_FOR_ALTIUM_OVERRIDE= 
SET APPDATA=C:\Users\Pengzhihui\AppData\Roaming
SET asl.log=Destination=file
SET CLASSPATH=.;C:\Program Files\Java\jdk1.8.0_92\lib\dt.jar;C:\Program Files\Java\jdk1.8.0_92\lib\tools.jar;
SET CommonProgramFiles=C:\Program Files\Common Files
SET CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
SET CommonProgramW6432=C:\Program Files\Common Files
SET COMPUTERNAME=ZHIHUIDEXPS
SET ComSpec=C:\WINDOWS\system32\cmd.exe
SET DriverData=C:\Windows\System32\Drivers\DriverData
SET HOMEDRIVE=C:
SET HOMEPATH=\Users\Pengzhihui
SET INTEL_DEV_REDIST=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\
SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0_92
SET KENDRYTE_IDE_LOCAL_PACKAGE_DIR=D:\Green\KendryteIDE\LocalPackage
SET KENDRYTE_IDE_UPDATER=D:\Green\KendryteIDE\Updater\electron.exe
SET KENDRYTE_IDE_UPDATER_CONTENT_ROOT=D:\Green\KendryteIDE
SET KENDRYTE_IDE_UPDATER_IS_BUILT=yes
SET KENDRYTE_IDE_UPDATER_PIPE=\\?\pipe\C:\Users\PENGZH~1\AppData\Local\Temp\KendryteIDE_Cache\27673_updater.sock
SET KENDRYTE_IDE_UPDATER_PIPE_ID=1
SET KEYSHOT8=C:\Users\Pengzhihui\Documents\KeyShot 8
SET LOCALAPPDATA=C:\Users\Pengzhihui\AppData\Local
SET LOGONSERVER=\\ZHIHUIDEXPS
SET MIC_LD_LIBRARY_PATH=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\compiler\lib\intel64_win_mic
SET NUMBER_OF_PROCESSORS=4
SET OneDrive=E:\OneDrive
SET OS=Windows_NT
SET Path=d:\Green\KendryteIDE\bin;D:\Green\KendryteIDE\LocalPackage\toolchain\bin;D:\Green\KendryteIDE\LocalPackage\cmake\bin;D:\Green\KendryteIDE\LocalPackage\jlink;D:\Green\KendryteIDE\LocalPackage\clang-format\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH
SET PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
SET PROCESSOR_ARCHITECTURE=AMD64
SET PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
SET PROCESSOR_LEVEL=6
SET PROCESSOR_REVISION=8e09
SET ProgramData=C:\ProgramData
SET ProgramFiles=C:\Program Files
SET ProgramFiles(x86)=C:\Program Files (x86)
SET ProgramW6432=C:\Program Files
SET PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
SET PUBLIC=C:\Users\Public
SET PVIEW_KEYSHOT7_HOME=D:\Program Files\KeyShot7\bin\
SET PVIEW_KEYSHOT8_HOME=D:\Program Files\KeyShot\bin\
SET SESSIONNAME=Console
SET SystemDrive=C:
SET SystemRoot=C:\WINDOWS
SET SYSTEM_TEMP=C:\Users\PENGZH~1\AppData\Local\Temp
SET TEMP=C:\Users\PENGZH~1\AppData\Local\Temp\KendryteIDE_Cache
SET TMP=C:\Users\PENGZH~1\AppData\Local\Temp\KendryteIDE_Cache
SET TMPDIR=C:\Users\PENGZH~1\AppData\Local\Temp\KendryteIDE_Cache
SET USERDOMAIN=ZHIHUIDEXPS
SET USERDOMAIN_ROAMINGPROFILE=ZHIHUIDEXPS
SET USERNAME=Pengzhihui
SET USERPROFILE=C:\Users\Pengzhihui
SET VSCODE_CWD=D:\Green\KendryteIDE\Updater
SET VSCODE_IPC_HOOK=\\.\pipe\4a333cc96d3b17bce5da4ad13e6be33f-1.34.1-beta-main-sock
SET VSCODE_LOGS=D:\Green\KendryteIDE\UserData\latest\user-data\logs\20191024T175443
SET VSCODE_NLS_CONFIG={"locale":"zh-cn","availableLanguages":{"*":"zh-cn"},"_languagePackId":"2ae16f5a9a23c98b985a67d503c3ac22.zh-cn","_translationsConfigFile":"D:\\Green\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\tcf.json","_cacheRoot":"D:\\Green\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn","_resolvedLanguagePackCoreLocation":"D:\\Green\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\e4de46724de34a5f46541818e9fee25971ac9969","_corruptedFile":"D:\\Green\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\corrupted.info","_languagePackSupport":true}
SET VSCODE_NODE_CACHED_DATA_DIR=D:\Green\KendryteIDE\UserData\latest\user-data\CachedData\e4de46724de34a5f46541818e9fee25971ac9969
SET VSCODE_PATH=D:\Green\KendryteIDE\Application\app_1.34.1-beta_20190802.2
SET VSCODE_PID=2112
SET VSCODE_PORTABLE=D:\Green\KendryteIDE\UserData\latest
SET windir=C:\WINDOWS
SET XILINX_FOR_ALTIUM_OVERRIDE= 
SET PYTHONHOME=D:/Green/KendryteIDE/LocalPackage/python2library
SET PYTHONPATH=D:/Green/KendryteIDE/LocalPackage/python2library;D:/Green/KendryteIDE/LocalPackage/toolchain/share/gdb/python
SET PYTHONDONTWRITEBYTECODE=yes
SET CMAKE_MAKE_PROGRAM=make
SET KENDRYTE_IDE=yes
SET LANG=en_US.utf-8
"D:/Green/KendryteIDE/LocalPackage/cmake/bin/cmake.exe" --build c:/Users/Pengzhihui/Desktop/Tmp/A-Eye/firmware/build -- -j 3